package myframe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gength
 */
import java.awt.HeadlessException;
import java.lang.String;
import java.lang.Double;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;

public class Form2 extends javax.swing.JFrame {

    DefaultTableModel model;
  

    DecimalFormat df = new DecimalFormat("#,###.00");
    /**
     * Creates new form Form2
     */
    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;

    String x;
    double ans;
    double total = 0.0;
    int selected;

    public Form2() {
        initComponents();
        String[] col = {"id", "name", "number", "price", "date"};
        model = new DefaultTableModel(col, 0);
        tbsave.setModel(model);
        con = Connect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsave = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbproduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnumber = new javax.swing.JTextField();
        jTextFieldprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        lbtotal = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextFielddate = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        tbsave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_product", "name_product", "number_product", "price_product", "date_product"
            }
        ));
        tbsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsaveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsave);

        tbproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_product", "name_product", "lot_product", "number_product"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbproduct);
        if (tbproduct.getColumnModel().getColumnCount() > 0) {
            tbproduct.getColumnModel().getColumn(0).setResizable(false);
            tbproduct.getColumnModel().getColumn(1).setResizable(false);
            tbproduct.getColumnModel().getColumn(2).setResizable(false);
            tbproduct.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ค้นหายา");

        jTextFieldsearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsearchActionPerformed(evt);
            }
        });
        jTextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("จำนวน");

        jTextFieldnumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumberActionPerformed(evt);
            }
        });
        jTextFieldnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldnumberKeyReleased(evt);
            }
        });

        jTextFieldprice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ราคา");

        jLabel4.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("รหัสยา");

        jTextFieldid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jButton1.setText("ลบรายการ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jButton2.setText("บันทึกรายการ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ชื่อยา");

        jTextFieldname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbtotal.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        lbtotal.setForeground(new java.awt.Color(255, 255, 255));
        lbtotal.setText("ราคารวม");

        jButton3.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jButton3.setText("บันทึกการขาย");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextFielddate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFielddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddateActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("วันที่");

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\BrighT\\Desktop\\SA\\x-button.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldid, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jTextFielddate)
                                    .addComponent(jTextFieldname)
                                    .addComponent(jTextFieldnumber)
                                    .addComponent(jTextFieldprice)))
                            .addComponent(lbtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton3)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(566, 566, 566)
                    .addComponent(date)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFielddate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(date)
                    .addContainerGap(662, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsearchActionPerformed

    private void jTextFieldnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumberActionPerformed

    private void jTextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyReleased
        // TODO add your handling code here:
        try {
            String data = jTextFieldsearch.getText();
            String sql = "Select sale.id_product ,pharmacy.name_product,sale.lot_product,sale.number_product"
                    + " from sale INNER JOIN pharmacy "
                    + "ON sale.id_product = pharmacy.id_product "
                    + "where sale.id_product=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, data);
            rs = pst.executeQuery();
            tbproduct.setModel(DbUtils.resultSetToTableModel(rs));
            System.out.println(sql);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextFieldsearchKeyReleased

    private void jTextFieldnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumberKeyReleased
        //String getid = jTextFieldid.getText();
        String sql = "select * from pharmacy where id_product='" + jTextFieldid.getText() + "'";
        int price = 0;
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                x = rs.getString("price_product");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form2.class.getName()).log(Level.SEVERE, null, ex);
        }
        ans = Double.valueOf(x) * Double.valueOf(jTextFieldnumber.getText());
        //df.format(ans);
        jTextFieldprice.setText(Double.toString(ans));

    }//GEN-LAST:event_jTextFieldnumberKeyReleased

    private void tbproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductMouseClicked
        try {
            // TODO add your handling code here:
            int row = tbproduct.getSelectedRow();
            String selectid = tbproduct.getValueAt(row, 0).toString();
            String sql = "select * from pharmacy where id_product='" + selectid + "'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("id_product");
                jTextFieldid.setText(add1);
                String add2 = rs.getString("name_product");
                jTextFieldname.setText(add2);
            }
            //jTextFieldid.setText(selectid);
        } catch (SQLException ex) {
            Logger.getLogger(Form2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbproductMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tbsave.isRowSelected(selected)) {
            double moneySelected = Double.valueOf(tbsave.getValueAt(selected, 3).toString().replace(",", ""));
            System.out.println("แสดงจำนวนเงิน" + moneySelected);
            total -= moneySelected;
            lbtotal.setText("ราคารวม  : " + df.format(total) + " บาท");
            if (total == 0) {
                lbtotal.setText("ราคารวม  : 0.00 บาท");
            }
            model.removeRow(selected);
        } else {
            JOptionPane.showMessageDialog(this, "กรุณาเลือกแถวที่ต้องการลบ", "คำเตือน", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldid.getText().isEmpty() || jTextFieldname.getText().isEmpty() || jTextFieldnumber.getText().isEmpty() || jTextFieldprice.getText().isEmpty() || jTextFielddate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "กรุณาใส่ข้อมูลให้ครบ", "คำเตือน", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] data = {jTextFieldid.getText(), jTextFieldname.getText(), jTextFieldnumber.getText(), jTextFieldprice.getText(), jTextFielddate.getText()};
            total += ans;
            model.addRow(data);
            lbtotal.setText("ราคารวม  : " + df.format(total) + " บาท");
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsaveMouseClicked
        // TODO add your handling code here:
        selected = tbsave.getSelectedRow();
    }//GEN-LAST:event_tbsaveMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {

            int rows = tbsave.getRowCount();

            for (int row = 0; row < rows; row++) {
                String idsale = (String) tbsave.getValueAt(row, 0);
                String numbersale = (String) tbsave.getValueAt(row, 2);
                String datesale = (String) tbsave.getValueAt(row, 4);
                String sql = "Insert into savesale(id_sale,number_sale,date_sale) values ('" + idsale + "','" + numbersale + "','" + datesale + "')";

                pst = con.prepareStatement(sql);
                pst.execute();
            }
            JOptionPane.showMessageDialog(null, "Successfully Save");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTextFieldsearch.setText("");
            jTextFielddate.setText("");
            jTextFieldid.setText("");
            jTextFieldname.setText("");
            jTextFieldnumber.setText("");
            jTextFieldprice.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFielddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFielddate;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldnumber;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTable tbproduct;
    private javax.swing.JTable tbsave;
    // End of variables declaration//GEN-END:variables
}
